spring:
  datasource:
    name: credit_yun
    url: jdbc:mysql://localhost:3306/health-manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true


shiro:
  expire: 30 #默认过期时间
  password:
    hash-iterations: 10 #默认加密次数,在密码匹配和注册两个地方使用
    algorithm-name: sha-1 #加密算法
#  thymeleaf:
#    prefix: /templates
#    suffix: .html
#    cache: false
#    servlet:
#      content-type: text/html
#    mode: LEGACYHTML5