spring:
  datasource:
    name: credit_yun
    url: jdbc:mysql://47.92.72.146:3306/health-manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
shiro:
  expire: 30 #默认过期时间
  password:
    hash-iterations: 10 #默认加密次数,在密码匹配和注册两个地方使用
    algorithm-name: sha-1 #加密算法
#  thymeleaf:
#    prefix: /templates
#    suffix: .html
#    cache: false
#    servlet:
#      content-type: text/html
#    mode: LEGACYHTML5